# Generated by Django 5.0.4 on 2024-04-17 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='пользователь')),
                ('text', models.TextField(verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('capacity', models.IntegerField(verbose_name='Количество мест')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='фото')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='фото')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='фото')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='room_images/', verbose_name='фото')),
                ('price', models.IntegerField(default=1000, verbose_name='цена')),
                ('wifi', models.BooleanField(default=True, verbose_name=True)),
                ('size', models.IntegerField(blank=True, null=True, verbose_name='Размер комнаты')),
                ('tv', models.BooleanField(blank=True, default=False, null=True, verbose_name='Телевизор')),
                ('air_conditioner', models.BooleanField(blank=True, default=False, null=True, verbose_name='Кондиционер')),
                ('fan', models.BooleanField(blank=True, default=False, null=True, verbose_name='Фен')),
                ('shower', models.BooleanField(blank=True, default=False, null=True, verbose_name='Душ')),
                ('beds', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel_app.bed', verbose_name='Кровать')),
                ('cats', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel_app.category', verbose_name='Категории')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel_app.meal', verbose_name='Питание')),
            ],
        ),
    ]
