# Generated by Django 4.2.11 on 2024-04-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='фото'),
            preserve_default=False,
        ),
    ]
