# Generated by Django 5.0.4 on 2024-04-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.IntegerField(default=1000, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(upload_to='room_images/', verbose_name='фото'),
        ),
    ]
